import './globals.css';
{
	/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link> */
}
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
import { Nunito } from 'next/font/google';

const nunito = Nunito({
	subsets: ['latin'],
	weight: ['400', '700'], // Specify the font weights you want to use
  });

export const metadata = {
	title: 'Ivydale',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={nunito.className}>{children}</body>
		</html>
	);
}
