version: "3.9"

services:
  app:
    container_name: ivydalefashion_backend
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./app:/code
    env_file:
      - .env  # Load environment variables from .env file
    command: >
      sh -c "
          python manage.py wait_for_db &&
          python manage.py migrate &&
          python manage.py createsuperuser --noinput || true &&
          python -m venv /app/venv &&
          /app/venv/bin/pip install watchdog &&
          /app/venv/bin/python -m watchdog.watchmedo auto-restart --directory=./app --pattern=*.py --recursive -- python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    container_name: ivydalefashion_db
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  dev-db-data: