version: "3.9"

services:
  app:
    container_name: ivydalefashion_backend
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./app:/code
    command: >
      sh -c "
          python manage.py wait_for_db &&
          python manage.py migrate &&
          python manage.py createsuperuser --noinput || true &&
          python -m venv /app/venv &&
          /app/venv/bin/pip install watchdog &&
          /app/venv/bin/python -m watchdog.watchmedo auto-restart --directory=./app --pattern=*.py --recursive -- python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=app.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=password
    depends_on:
      - db

  db:
    container_name: ivydalefashion_db
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: