import { Metadata } from 'next'
import BlogNavbarComponent from '../_components/BlogNavbarComponent'
import styles from '../_styles/blog.module.scss' // styling

// metadata
export const metadata: Metadata = {
  title: 'Ivydale Blog',
  description: 'Generated by create next app',
}

const BlogPage = () => {
  return (
    <main >
      <BlogNavbarComponent></BlogNavbarComponent>
      <h1 className={styles.header}> Blog page,, lotta articles

      </h1>
    </main>
  )
}

export default BlogPage;
