import React from 'react';
import { Metadata } from 'next';
import BlogNavbarComponent from '../_components/BlogNavbarComponent';
import styles from '../_styles/blog.module.scss'; // styling
import BlogPostsComponent from './blogPosts';

// metadata
export const metadata: Metadata = {
	title: 'Ivydale Blog',
	description: 'Generated by create next app',
};

const BlogPage = () => {
	return (
		<div>
			<BlogNavbarComponent></BlogNavbarComponent>

			<div className={styles.blogPosts}>
				<BlogPostsComponent></BlogPostsComponent>
			</div>
			
		</div>
	);
};

export default BlogPage;
