import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About Ivydale',
  description: 'Generated by create next app',
}

const AboutPage = () => {
    return (
      <div>
        <h1> About page</h1>
      </div>
    )
  }
  
export default AboutPage;