import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Ivydale Blog',
  description: 'Generated by create next app',
}

const BlogPage = () => {
  return (
    <main >
      <h1> Blog page</h1>
    </main>
  )
}

export default BlogPage;
