import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Ivydale Home',
  description: 'Generated by create next app',
}

const HomePage = () =>{
  return (
    <div>

      <h4 style={{
        'color': 'blue',
        'textDecoration': 'underline'
      }}>
         <Link href="/Cart">cart!</Link>
      </h4>

    </div>
    
  )
}

export default HomePage;