import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Ivydale Home',
  description: 'Generated by create next app',
}

const HomePage = () =>{
  return (
    <div>HomePage</div>
  )
}

export default HomePage;