import { Metadata } from 'next'
import Link from 'next/link'
import {Form, Button} from 'react-bootstrap'
// import styles from '../_styles/signin.module.scss'
import MainNavbar from '../_components/Header'
import MiniNavbar from '../_components/HeaderMini'
import SinginComponent from './signinComponent'

export const metadata: Metadata = {
  title: 'Ivydale Blog',
  description: 'Generated by create next app',
}

const SigninPage = () => {
   
  return (
    <main >
        <MiniNavbar></MiniNavbar>
        {/* <MainNavbar></MainNavbar> */}
        <SinginComponent></SinginComponent>
        {/* <Footer></Footer> */}
    </main>
    )
  }

export default SigninPage;