import React from 'react';
import { Metadata } from 'next';
import CommerceComponent from './_commerceComponent';
import Footer from '../_components/Footer';
import Header from '../_components/Header'

export const metadata: Metadata = {
	title: 'Ivydale Blog',
	description: 'Generated by create next app',
};

const LandingPage = () => {
	return (
		<div>
			<Header></Header>
			<CommerceComponent></CommerceComponent>
			<Footer></Footer>
		</div>
	);
};

export default LandingPage;
