import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Ivydale Blog',
  description: 'Generated by create next app',
}

const LandingPage = () => {
    return (
      <main >
        <h1> Commerce page</h1>
      </main>
    )
  }

export default LandingPage;